<?php

declare(strict_types=1);

namespace SBUERK\ModernExtbaseFrontendEdit\Tests\Functional\Frontend;

use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\Attributes\Test;

/**
 * The `list` plugin, rendered through a real frontend request.
 *
 * What is under test is the whole chain and not the controller: the `CType`
 * registered by `Configuration/TCA/Overrides/tt_content.php`, the rendering
 * definition generated by `ExtensionUtility::configurePlugin()`, the classic
 * TypoScript of `ext_localconf.php`, the display repository with its storage
 * page and enable field constraints, and the Fluid templates including every
 * label they resolve.
 *
 * Labels are asserted by their **text**, never by the markup that surrounds
 * them. A missing `trans-unit` renders as an empty string, so a test asserting
 * only that a `<h2>` exists passes with every label gone.
 */
final class ProfileListPluginTest extends AbstractProfilePluginTestCase
{
    #[Test]
    public function listRendersTheVisibleProfilesOfTheConfiguredStoragePage(): void
    {
        $response = $this->renderListPlugin();

        $this->assertSame(200, $response->getStatusCode());

        $renderedNames = array_keys($this->profileCards((string)$response->getBody()));
        sort($renderedNames);

        $this->assertSame(['Ada Lovelace', 'Radia Perlman'], $renderedNames);
    }

    /**
     * The three records that must not appear, each excluded for a different
     * reason. They are asserted in one test on purpose: what matters is that
     * the rendered body contains none of them, and a body that contains one
     * names it in the failure message.
     *
     * @return \Generator<string, array{name: string}>
     */
    public static function invisibleProfileNames(): \Generator
    {
        yield 'hidden profile' => ['name' => 'Grace Hopper'];
        yield 'deleted profile' => ['name' => 'Karen Sparck Jones'];
        yield 'profile outside the storage page' => ['name' => 'Anita Borg'];
    }

    #[DataProvider('invisibleProfileNames')]
    #[Test]
    public function listRendersNeitherHiddenNorDeletedNorOutOfScopeProfiles(string $name): void
    {
        $response = $this->renderListPlugin();

        $this->assertStringNotContainsString($name, (string)$response->getBody());
    }

    /**
     * Every label the list renders, by its text.
     *
     * `list.heading` and `link.show` are the two the plugin cannot render
     * without, and both were missing from `locallang.xlf` at one point without
     * anything failing.
     */
    #[Test]
    public function listResolvesEveryLabelItRenders(): void
    {
        $body = (string)$this->renderListPlugin()->getBody();

        $this->assertStringContainsString('<h2>Profiles</h2>', $body);

        foreach ($this->profileCards($body) as $name => $card) {
            $this->assertStringContainsString(
                'View profile',
                $card,
                sprintf('The card of "%s" renders the "link.show" label.', $name),
            );
        }
    }

    /**
     * The label of the empty listing, which needs a storage page without
     * profiles to become visible at all.
     */
    #[Test]
    public function listRendersTheEmptyLabelWhenTheStoragePageHoldsNoProfile(): void
    {
        $this->addTypoScriptToTemplateRecord(
            self::STORAGE_PAGE_ID,
            'plugin.tx_modernextbasefrontendedit.persistence.storagePid = ' . self::EDIT_PAGE_ID . LF,
        );

        $body = (string)$this->renderListPlugin()->getBody();

        $this->assertStringContainsString('No profiles available.', $body);
        $this->assertSame([], $this->profileCards($body));
    }

    /**
     * The link to the detail page, per entry.
     *
     * Asserted through the profile argument rather than through the full URI:
     * the argument order of an Extbase URI is not part of any contract, the
     * page it points at and the record it carries are.
     */
    #[Test]
    public function everyEntryLinksToTheConfiguredDetailPageWithItsOwnProfile(): void
    {
        $cards = $this->profileCards((string)$this->renderListPlugin()->getBody());

        $this->assertStringContainsString('href="/profiles?', $cards['Ada Lovelace']);
        $this->assertStringContainsString(
            'tx_modernextbasefrontendedit_show%5Bprofile%5D=1',
            $cards['Ada Lovelace'],
        );
        $this->assertStringContainsString(
            'tx_modernextbasefrontendedit_show%5Bprofile%5D=4',
            $cards['Radia Perlman'],
        );
    }

    /**
     * An anonymous visitor owns nothing, so no entry carries an edit link.
     *
     * This is the case the ownership resolver denies first: `UserAspect` yields
     * `0` for a visitor without a session, and `0` is a value the owner column
     * of a record can genuinely hold.
     */
    #[Test]
    public function listRendersNoEditLinkForAnAnonymousVisitor(): void
    {
        $body = (string)$this->renderListPlugin()->getBody();

        $this->assertStringNotContainsString('Edit profile', $body);
        $this->assertStringNotContainsString('/edit-profile', $body);
    }

    /**
     * @return \Generator<string, array{frontendUserId: int, ownedProfileName: string, foreignProfileName: string}>
     */
    public static function frontendUsersAndTheirProfiles(): \Generator
    {
        yield 'frontend user 1 owns Ada Lovelace' => [
            'frontendUserId' => self::OWNER_FRONTEND_USER_ID,
            'ownedProfileName' => 'Ada Lovelace',
            'foreignProfileName' => 'Radia Perlman',
        ];
        yield 'frontend user 2 owns Radia Perlman' => [
            'frontendUserId' => self::OTHER_FRONTEND_USER_ID,
            'ownedProfileName' => 'Radia Perlman',
            'foreignProfileName' => 'Ada Lovelace',
        ];
    }

    /**
     * The behaviour the ownership resolver exists for.
     *
     * Both profiles are rendered for both users — the edit link is the only
     * difference, and it is asserted per card rather than per page.
     */
    #[DataProvider('frontendUsersAndTheirProfiles')]
    #[Test]
    public function listRendersTheEditLinkOnlyForAProfileTheLoggedInUserOwns(
        int $frontendUserId,
        string $ownedProfileName,
        string $foreignProfileName,
    ): void {
        $cards = $this->profileCards((string)$this->renderListPlugin($frontendUserId)->getBody());

        $this->assertStringContainsString('href="/edit-profile"', $cards[$ownedProfileName]);
        $this->assertStringContainsString('Edit profile', $cards[$ownedProfileName]);

        $this->assertStringNotContainsString('/edit-profile', $cards[$foreignProfileName]);
        $this->assertStringNotContainsString('Edit profile', $cards[$foreignProfileName]);
    }
}
