<?php

declare(strict_types=1);

namespace SBUERK\ModernExtbaseFrontendEdit\Tests\Functional\Frontend;

use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\Attributes\Test;

/**
 * The `list` plugin, rendered through a real frontend request.
 *
 * What is under test is the whole chain and not the controller: the `CType`
 * registered by `Configuration/TCA/Overrides/tt_content.php`, the rendering
 * definition generated by `ExtensionUtility::configurePlugin()`, the classic
 * TypoScript of `ext_localconf.php`, the display repository with its storage
 * page and enable field constraints, and the Fluid templates including every
 * label they resolve.
 *
 * Labels are asserted by their **text**, never by the markup that surrounds
 * them. A missing `trans-unit` renders as an empty string, so a test asserting
 * only that a `<h2>` exists passes with every label gone.
 *
 * ## What is deliberately not covered here
 *
 * The `Profile/Image` partial and the `profile.image.alt` label it is passed:
 * no fixture profile carries a profile image, so both plugins render the
 * partial into an empty string and every assertion below holds with the partial
 * gone. Covering it needs `sys_file` and `sys_file_reference` fixtures plus a
 * file on disk in the test instance, which belongs with the change that owns
 * the image handling rather than with the plugins. Until then this is a stated
 * gap, not a covered case.
 */
final class ProfileListPluginTest extends AbstractProfilePluginTestCase
{
    #[Test]
    public function listRendersTheVisibleProfilesOfTheConfiguredStoragePage(): void
    {
        $response = $this->renderListPlugin();

        $this->assertSame(200, $response->getStatusCode());

        $renderedNames = array_keys($this->profileCards((string)$response->getBody()));
        sort($renderedNames);

        $this->assertSame(self::LISTED_PROFILE_NAMES, $renderedNames);
    }

    /**
     * The shortname fallback of `Profile/Card`.
     *
     * A profile may carry neither a first nor a last name — only the shortname
     * is required by the edit form — and the heading then falls back to it.
     * Asserted through the card key, which *is* the trimmed content of the
     * name heading: without the fallback that heading renders empty, and the
     * card is then keyed by the empty string instead.
     */
    #[Test]
    public function cardOfAProfileWithoutNamesFallsBackToItsShortname(): void
    {
        $cards = $this->profileCards((string)$this->renderListPlugin()->getBody());

        $this->assertArrayHasKey(self::SHORTNAME_ONLY_PROFILE_NAME, $cards);
        $this->assertArrayNotHasKey('', $cards);
    }

    /**
     * The three records that must not appear, each excluded for a different
     * reason. They are asserted in one test on purpose: what matters is that
     * the rendered body contains none of them, and a body that contains one
     * names it in the failure message.
     *
     * @return \Generator<string, array{name: string}>
     */
    public static function invisibleProfileNames(): \Generator
    {
        yield 'hidden profile' => ['name' => 'Grace Hopper'];
        yield 'deleted profile' => ['name' => 'Karen Sparck Jones'];
        yield 'profile outside the storage page' => ['name' => 'Anita Borg'];
    }

    #[DataProvider('invisibleProfileNames')]
    #[Test]
    public function listRendersNeitherHiddenNorDeletedNorOutOfScopeProfiles(string $name): void
    {
        $body = (string)$this->renderListPlugin()->getBody();

        // The card set is asserted first, and it is what makes the body check
        // below mean "excluded" rather than "the plugin rendered nothing at
        // all" — a substring that is absent from an empty page proves nothing.
        $cards = $this->profileCards($body);
        $renderedNames = array_keys($cards);
        sort($renderedNames);
        $this->assertSame(self::LISTED_PROFILE_NAMES, $renderedNames);
        $this->assertArrayNotHasKey($name, $cards);

        $this->assertStringNotContainsString($name, $body);
    }

    /**
     * Every label the list renders, by its text.
     *
     * `list.heading` and `link.show` are the two the plugin cannot render
     * without, and both were missing from `locallang.xlf` at one point without
     * anything failing.
     */
    #[Test]
    public function listResolvesEveryLabelItRenders(): void
    {
        $body = (string)$this->renderListPlugin()->getBody();

        $this->assertStringContainsString('<h2>Profiles</h2>', $body);

        // Without this the loop below is allowed to make no assertion at all,
        // and the test would stay green for a plugin that renders no card.
        $cards = $this->profileCards($body);
        $this->assertNotSame([], $cards);

        foreach ($cards as $name => $card) {
            $this->assertStringContainsString(
                'View profile',
                $card,
                sprintf('The card of "%s" renders the "link.show" label.', $name),
            );
        }
    }

    /**
     * The label of the empty listing, which needs a storage page without
     * profiles to become visible at all.
     */
    #[Test]
    public function listRendersTheEmptyLabelWhenTheStoragePageHoldsNoProfile(): void
    {
        $this->addTypoScriptToTemplateRecord(
            self::STORAGE_PAGE_ID,
            'plugin.tx_modernextbasefrontendedit.persistence.storagePid = ' . self::EDIT_PAGE_ID . LF,
        );

        $body = (string)$this->renderListPlugin()->getBody();

        $this->assertStringContainsString('No profiles available.', $body);
        $this->assertSame([], $this->profileCards($body));
    }

    /**
     * The link to the detail page, per entry.
     *
     * Asserted through the profile argument rather than through the full URI:
     * the argument order of an Extbase URI is not part of any contract, the
     * page it points at and the record it carries are.
     */
    #[Test]
    public function everyEntryLinksToTheConfiguredDetailPageWithItsOwnProfile(): void
    {
        $cards = $this->profileCards((string)$this->renderListPlugin()->getBody());

        $this->assertStringContainsString('href="/profiles?', $cards['Ada Lovelace']);
        $this->assertStringContainsString(
            'tx_modernextbasefrontendedit_show%5Bprofile%5D=1',
            $cards['Ada Lovelace'],
        );
        $this->assertStringContainsString(
            'tx_modernextbasefrontendedit_show%5Bprofile%5D=4',
            $cards['Radia Perlman'],
        );
    }

    /**
     * An anonymous visitor owns nothing, so no entry carries an edit link.
     *
     * This is the case the ownership resolver denies first: `UserAspect` yields
     * `0` for a visitor without a session, and `0` is a value the owner column
     * of a record can genuinely hold.
     *
     * The card of {@see UNOWNED_PROFILE_UID} is what gives the assertion teeth.
     * Every other listed profile has a non-zero owner and would be excluded by
     * the `feUser = 0` comparison alone, so a body-wide check over them stays
     * green with both guards removed. This one record matches that comparison,
     * and it is the record an anonymous visitor would be offered an edit link
     * for.
     */
    #[Test]
    public function listRendersNoEditLinkForAnAnonymousVisitor(): void
    {
        $body = (string)$this->renderListPlugin()->getBody();
        $cards = $this->profileCards($body);

        $this->assertArrayHasKey(self::UNOWNED_PROFILE_NAME, $cards);
        $this->assertStringNotContainsString('Edit profile', $cards[self::UNOWNED_PROFILE_NAME]);
        $this->assertStringNotContainsString('/edit-profile', $cards[self::UNOWNED_PROFILE_NAME]);

        $this->assertStringNotContainsString('Edit profile', $body);
        $this->assertStringNotContainsString('/edit-profile', $body);
    }

    /**
     * A profile without an owner belongs to nobody, not to everybody.
     *
     * The counterpart of the test above for a *logged-in* user: `fe_user = 0`
     * must not match a real user id either, which is the `feUser = 0`
     * comparison rather than the anonymous guards.
     */
    #[Test]
    public function listRendersNoEditLinkForAProfileWithoutAnOwner(): void
    {
        $cards = $this->profileCards(
            (string)$this->renderListPlugin(self::OWNER_FRONTEND_USER_ID)->getBody(),
        );

        $this->assertArrayHasKey(self::UNOWNED_PROFILE_NAME, $cards);
        $this->assertStringNotContainsString('Edit profile', $cards[self::UNOWNED_PROFILE_NAME]);
        $this->assertStringNotContainsString('/edit-profile', $cards[self::UNOWNED_PROFILE_NAME]);
    }

    /**
     * @return \Generator<string, array{frontendUserId: int, ownedProfileName: string, foreignProfileName: string}>
     */
    public static function frontendUsersAndTheirProfiles(): \Generator
    {
        yield 'frontend user 1 owns Ada Lovelace' => [
            'frontendUserId' => self::OWNER_FRONTEND_USER_ID,
            'ownedProfileName' => 'Ada Lovelace',
            'foreignProfileName' => 'Radia Perlman',
        ];
        yield 'frontend user 2 owns Radia Perlman' => [
            'frontendUserId' => self::OTHER_FRONTEND_USER_ID,
            'ownedProfileName' => 'Radia Perlman',
            'foreignProfileName' => 'Ada Lovelace',
        ];
    }

    /**
     * The behaviour the ownership resolver exists for.
     *
     * Both profiles are rendered for both users — the edit link is the only
     * difference, and it is asserted per card rather than per page.
     */
    #[DataProvider('frontendUsersAndTheirProfiles')]
    #[Test]
    public function listRendersTheEditLinkOnlyForAProfileTheLoggedInUserOwns(
        int $frontendUserId,
        string $ownedProfileName,
        string $foreignProfileName,
    ): void {
        $cards = $this->profileCards((string)$this->renderListPlugin($frontendUserId)->getBody());

        $this->assertStringContainsString('href="/edit-profile"', $cards[$ownedProfileName]);
        $this->assertStringContainsString('Edit profile', $cards[$ownedProfileName]);

        $this->assertStringNotContainsString('/edit-profile', $cards[$foreignProfileName]);
        $this->assertStringNotContainsString('Edit profile', $cards[$foreignProfileName]);
    }
}
